#!/bin/bash

# Get the list of authors from Git commit history
authors=$(git log --format="%an <%ae>" | sort -u)

# Print the header
echo "# File generated by generate-authors.sh. DO NOT EDIT."
echo "# This file lists all contributors to the repository."
echo "# See generate-authors.sh to make modifications."

# Print the authors
echo "$authors"
